; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:m5stamp-pico]
platform          = espressif32
board             = m5stamp-pico
framework         = arduino
monitor_speed     = 115200
build_flags       = -DCORE_DEBUG_LEVEL=3

; Bluepad32を利用するためのカスタムプラットフォームパッケージ等の設定
; （※PlatformIOでBluepad32公式が推奨する環境設定を適用します）
platform_packages = framework-arduinoespressif32 @ https://github.com/ricardoquesada/esp32-arduino-lib-builder/releases/download/4.1.0/esp32-bluepad32-4.1.0.zip
lib_deps = Links2004/WebSockets
board_build.filesystem = littlefs
board_build.partitions = partitions.csv
